IQClass/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('course/', include('course.urls', namespace= 'courses')),
    path('home/', include('home.urls', namespace= 'home')),
    

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import path, include
from . import views

app_name = 'course'
urlpatterns = [
    
    path('', views.course_list, name = 'course_list'),
    path('<str:slug>', views.course_detail, name= 'course_detail' ),

       
    
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'course'
urlpatterns = [
    
    path('', views.home, name = 'home'),
  
     
    
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

course/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.timezone import now
# Create your models here.

def image_upload(instance, filename):
    imagename, extenstion = filename.split(".")
    return "course-list/%s.%s"%(instance.id, extenstion)


SKILL_CHOICES = (
    ('Beginner ', 'Beginner'),
    ('Intermediate', 'Intermediate'),
    ('Advanced', 'Advanced'),
   
)

CERTIFICATE_CHOICES = (
    ('Yes', 'Yes'),
    ('No', 'No'),
   
)



class Course(models.Model): # Table 

    
    title = models.CharField(max_length= 100)  # column 
    description = models.TextField(max_length= 2000)
    details = models.TextField(max_length= 2000)
    published_at =  models.DateTimeField(auto_now= True)
    price_previou = models.IntegerField(default=1)
    price_now = models.IntegerField(default=0)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload)
    slug = models.SlugField(blank=True, null= True)

    #Add 
    days = models.IntegerField(default=1)
    duration = models.IntegerField(default=1)
    certification = models.CharField(max_length=15, choices = CERTIFICATE_CHOICES)
    skill = models.CharField(max_length=15, choices = SKILL_CHOICES)
    when = models.DateTimeField(default=now)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Course,self).save(*args, **kwargs)

    def __str__(self):
    	return self.title

class Category( models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

home/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

course/views.py
from django.shortcuts import render
from .models import Course
from django.core.paginator import Paginator
from .filters import CourseFilter
# Create your views here.

def course_list(request):
    course_list = Course.objects.all()

        ## filters 
    myfilter = CourseFilter(request.GET, queryset=course_list)
    job_list = myfilter.qs

    paginator = Paginator(job_list, 1) # Show 3 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'courses':page_obj, 'myfilter':myfilter }
 
    return render(request, 'course/course_list.html', context)


def course_detail(request, slug):

    course_detail = Course.objects.get(slug= slug)
    
    year = course_detail.when.year
    month = course_detail.when.month
    days = course_detail.when.day
    hours = course_detail.when.hour
    minutes = course_detail.when.minute
    seconds = course_detail.when.second

    context = {'course': course_detail, 'year':year, 'month':month, 'days':days, 'hours':hours, 'minutes':minutes, 'seconds':seconds}
    return render(request, 'course/course_detail.html', context)

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):



    context = { }
 
    return render(request, 'home.html', context)

course/templates/course/course_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

    </div><!-- bg-header -->
    <div class="course-list mg-top1 clearfix">
        <div class="container">
            <div class="col-30">
              
                <div class="sidebar-left sidebar-course">
                    <div class="widget widget-categories">
                        <div class="widget-title">
                            Filter
                            <span class="bg">
                                <i class="fa fa-angle-down" aria-hidden="true"></i>
                            </span>
                        </div>
                        
                        <form method='GET'>
                                {% bootstrap_form myfilter.form %}
                                <input type ="submit" value='Search' class="enroll w-100 mt-5">

                            </form>

                    </div>
                </div><!-- sidebar-left -->
            </div>


            <div class="col-70">
                <div class="thim-course-top">
                    <div class="course-index">
                        All prices are in DT
                    </div>
                    <div class="switch-layout">
                        <a >
                            <span class="icon-icons8-list-filled-480"></span>
                        </a>
                        <a >
                            <span class="icon-icons8-grid-view-480"></span>
                        </a>
                    </div>
                </div>




                
                <div class="content-course-list">
                    {% for course in courses %}


                    <div class="flat-course clearfix">

                        <div class="featured-post">

                            <div class="entry-image">
                                <img src="{{course.image.url}}" alt="images">
                            </div>
                        </div>
                        <div class="course-content clearfix">
                            <div class="wrap-course-content">
                                <h4>
                                    <a href="{% url 'courses:course_detail' course.slug %}">{{ course }}</a>
                                </h4>
                                <p>
                                    {{ course.description}} 
                                </p>
                                <div class="author-info">
                                    
                                    <div class="enroll">
                                        <a href="{% url 'courses:course_detail' course.slug %}">Enroll</a>
                                    </div>
                                </div>
                            </div>
                            <div class="wrap-rating-price">
                                <div class="meta-rate">
                                    <div class="rating">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <span>(4)</span>
                                    </div>
                                    <div class="price">
                                        <span class="price-previou">
                                            <del>{{course.price_previou}} DT</del>
                                        </span>
                                        <span class="price-now">{{course.price_now}} DT</span>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>

                
                  
                {% endfor %}
                </div>

                

                {% if courses.has_other_pages%}
                <div class="pagination">
                    <ul>
                      {% if courses.has_previous %}
                       <li><a href="?page={{ courses.previous_page_number }}" class="page-numbers"> <i class="ti-angle-left"><</a></li>
                      {% endif %}

                      {% for i in courses.paginator.page_range%}
                      <li><a href="?page{{i}}" class="page-numbers" ><span>{{i}}</a></li>
                      {% endfor %}  
                      {% if courses.has_next %}
                      <li><a href="?page={{ courses.next_page_number }}"  class="page-numbers">></a></li>
                      {% endif %}

                    </ul>
                </div><!-- pagination -->
                {% endif %}

            </div>
        </div>
    </div><!-- course-list -->

{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IQClass</title>

    <!-- Mobile Specific Metas-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!-- Bootstrap-->
    <link rel="stylesheet" href="{% static 'stylesheet/bootstrap.css' %}">

    <!-- Template Style-->
    <link rel="stylesheet" href="{% static 'stylesheet/font-awesome.css' %}"> 
    <link rel="stylesheet" href="{% static 'stylesheet/animate.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheet/style.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheet/shortcodes.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheet/jquery-fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheet/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheet/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheet/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheet/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'stylesheet/jquery.mCustomScrollbar.min.css' %}">

    <link href="{% static 'icon/favicon.ico" rel="shortcut icon'%}">
</head>
<body>
    <div id="loading-overlay">
        <div class="loader"></div>
    </div>
    <div class="bg-header">
        <div class="flat-header-blog">
            <div class="top-bar clearfix">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-md-8 col-sm-12 col-xs-12">
                            <ul class="information">
                                <li class="phone lt-sp003">
                                    <i class="fa fa-phone" aria-hidden="true"></i> +216 99 777 447
                                </li>
                                <li class="email">
                                    <i class="fa fa-envelope" aria-hidden="true"></i> iqclass.info@gmail.com 
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6 col-md-4 col-sm-12 col-xs-12">
                            <ul class="nav-sing">
                                <li><a href="#">Sing In</a></li>
                                <li><a href="#">Sing Up</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <header class="header menu-bar header-blog hv-menu-type2">
                <div class="container">
                    <div class="menu-bar-wrap clearfix">
                        <div id="logo" class="logo">
                            <a href="index.html"><img src="{% static 'images/logo/02.png' %}" alt="images"></a>
                        </div>
                        <div class="mobile-button"><span></span></div>
                        <div class="header-menu">
                            <nav id="main-nav" class="main-nav">
                                <ul class="menu">
                                    <li><a href="#">Home</a>
                                       
                                    </li>
                                    <li><a href="{% url 'courses:course_list' %}">Course</a>
                                       
                                    </li>
                                    <li><a href="#">About</a>
                                       
                                    </li>
                                    <li><a href="#">Blog</a>
                                    
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </header>
            <div class="page-title page-title-blog">
                <div class="page-title-inner">
                    <div class="breadcrumbs breadcrumbs-blog text-left">
                        <div class="container">
                            <div class="breadcrumbs-wrap">
                                <ul class="breadcrumbs-inner">
                                    <li><a href="index.html">Home</a></li>
                                    <li><a href="course-list.html">Course</a></li>
                                </ul>
                                <div class="title">
                                    Course
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- bg-header -->


    {% block body %}

    {% endblock body %}

    <footer id="footer" class="footer-type1">
        <div class="form-send-email">
            <div class="container">
                <form action="#" class="form-send">
                    <input type="search" placeholder="Enter your email...">
                    <button class="btn send-button bg-clff5f60">
                        Send
                    </button>
                </form>
            </div>
        </div>
        <div id="footer-widget">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-footer">
                       <div class="logo-footer">
                           <img src="{% static 'images/logo/04.png'%} " alt="images">
                       </div>
                    </div>
                    <div class="col-lg-2 col-company">
                        <h3 class="widget widget-title">
                            Company
                        </h3>
                        <ul class="widget-nav-menu">
                            <li><a href="#">About Company</a></li>

                        </ul>
                    </div>
                    <div class="col-lg-2 col-link">
                        <h3 class="widget widget-title">
                            Help Links
                        </h3>
                        <ul class="widget-nav-menu">
                            <li><a href="#">Student Support</a></li>

                        </ul>
                    </div>
                    <div class="col-lg-3 col-course">
                        <h3 class="widget widget-title">
                            Course
                        </h3>
                        <ul class="widget-nav-menu">
                            <li><a href="{% url 'courses:course_list' %}">Course</a></li>
                       
                        </ul>
                    </div>
                    <div class="col-lg-2 col-media">
                        <h3 class="widget widget-title">
                            Social Media
                        </h3>
                        <ul class="widget-social-media">
                            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="bottom" class="bottom-type1 clearfix has-spacer">
            <div id="bottom-bar-inner" class="container">
                <div class="bottom-bar-inner-wrap">
                    <div class="bottom-bar-content">
                        <div id="copyright">
                            © 
                            <span class="text-year">
                                2018
                            </span>
                            <span class="text-name">
                                Roy Design.
                            </span>
                            <span class="license">
                                <a href="#">All Rights Reserved</a>
                            </span>
                        </div>
                    </div>
                    <div class="bottom-bar-menu">
                        <ul class="bottom-nav">
                            <li class="menu-item"><a href="#">About Company</a></li>
                            <li class="menu-item"><a href="#">Privacy Policy</a></li>
                            <li class="menu-item"><a href="#">Help Center</a></li>
                            <li class="menu-item"><a href="#">Terms</a></li>
                            <li class="menu-item"><a href="#">Site Map</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <a id="scroll-top" class="show"></a>
    </footer><!-- footer -->
    
    <script src="{% static 'javascript/jquery.min.js' %}"></script>
    <script src="{% static 'javascript/rev-slider.js' %}"></script>
    <script src="{% static 'javascript/plugins.js' %}"></script>
    <script src="{% static 'javascript/jquery-countTo.js' %}"></script>
    <script src="{% static 'javascript/jquery-ui.js' %}"></script>
    <script src="{% static 'javascript/jquery-fancybox.js' %}"></script>
    <script src="{% static 'javascript/flex-slider.min.js' %}"></script>
    <script src="{% static 'javascript/scroll-img.js' %}"></script>
    <script src="{% static 'javascript/owl.carousel.min.js' %}"></script>
    <script src="{% static 'javascript/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'javascript/parallax.js' %}"></script>
    <script src="{% static 'javascript/jquery-isotope.js' %}"></script>
    <script src="{% static 'javascript/equalize.min.js' %}"></script>
    <script src="{% static 'javascript/main.js' %}"></script>

    <!-- slider -->
    <script src="{% static 'rev-slider/js/jquery.themepunch.tools.min.js' %}"></script>
    <script src="{% static 'rev-slider/js/jquery.themepunch.revolution.min.js' %}"></script>

    <!-- Load Extensions only on Local File Systems ! The following part can be removed on Server for On Demand Loading -->
    <script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.actions.min.js' %}"></script>
    <script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.carousel.min.js' %}"></script>
    <script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.kenburn.min.js' %}"></script>
    <script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.layeranimation.min.js' %}"></script>
    <script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.migration.min.js' %}"></script>
    <script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.navigation.min.js' %}"></script>
    <script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.parallax.min.js' %}"></script>
    <script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.slideanims.min.js' %}"></script>
    <script src="{% static 'rev-slider/js/extensions/extensionsrevolution.extension.video.min.js' %}"></script>
</body>
</html>